name: diffem
channels:
  - conda-forge
dependencies:
  - h5py=3.10.0
  - pip=25.3
  - python=3.10.19
  - pip:
    - --find-links https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
    - dm-pix==0.4.2
    - inox==0.5.0
    - datasets==4.4.1
    - click==8.3.1
    - hydra-core==1.3.2
    - numpy==2.2.6
    - tqdm==4.67.1
    - jax[cuda12]==0.6.2
    - jax-cuda12-pjrt==0.6.2
    - jax-cuda12-plugin==0.6.2
    - jaxlib==0.6.2
    - matplotlib==3.8.2
    - nvidia-cudnn-cu11~=8.9
    - optax==0.1.7
    - POT==0.9.3
    - scipy==1.12.0
    - seaborn==0.13.2
    - tqdm==4.66.1
    - wandb==0.16.2
